apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  annotations:
   service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  labels:
    svc: frontend
spec:
  type: LoadBalancer
  selector:
    app: udagram-frontend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80